let timelineElements = [
    {
      id: 1,
      title: 'Graduated from Santa Sabina College',
      location: 'abc',
      description: 'I first got exposed to programming, through an elective called Information and Software Technology, where I wrote a simple python quiz program. I completed my HSC and graduated in 2019.',
      date: 'November 2019',
      icon: 'School',
    },
    {
      id: 2,
      title: 'Started at UNSW',
      location: 'def',
      description: 'I started my Bachelor of Engineering, Software (Hons) degree. Throughout this year, I learned fundamental programming topics such as the Data Structures and Algorithms and developed confidence in C programming.',
      date: 'February 2020',
      icon: 'logo',
    },
    {
      id: 3,
      title: 'External Subcommitee Member at UNSW WIT',
      location: 'ghi',
      description: 'I probably made one of my best first year decisions, by joining UNSW WIT\'s (Women in Technology) External Team. While COVID had taken away most of the opportunities to be physically present on campus, I felt connected to the student community through society events.',
      date: 'March 2020 - November 2020',
      icon: 'logo',
    },
    {
      id: 4,
      title: 'Externals Executive at UNSW WIT',
      location: 'jkl',
      description: 'I was elected as the 2021 Externals Executive and led a team of 6 members to establish and maintain relationships with over 20 sponsors. With the support of sponsors, WIT hosted 30+ events that allowed students to gain insight into the IT industry.',
      date: 'November 2020 - November 2021',
      icon: 'logo',
    },
    {
      id: 5,
      title: 'Careers Director at UNSW CSESoc',
      location: 'jkl',
      description: 'I was elected as a Careers Director and led a team of 12 subcommitee members, with 3 Co-Directors. I continued to plan and host events with sponsors, following my passion to bridge the gap between my fellow peers in university and industry professionals.',
      date: 'November 2021 - November 2022',
      icon: 'logo',
    },
    {
      id: 6,
      title: 'Software Engineering Intern at National Australia Bank',
      location: 'jkl',
      description: 'In my first job in the tech industry, I developed, tested and maintained microservices essential to NAB\'s payment orchestration workflow, using the Java Springboot Framework.',
      date: 'February 2022 - February 2023',
      icon: 'logo',
    },
    {
      id: 7,
      title: 'Academic Tutor, School of CSE UNSW',
      location: 'jkl',
      description: 'Through this role, I have the privilege of contributing to the course\'s mission to empower students with the knowledge and confidence to build web applications according to industry standards.',
      date: 'February 2023 - present',
      icon: 'logo',
    },
  ];
  
  export default timelineElements; 